// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-Nndek8zOrmeNL4Zo_c5PVxjl-QI9xI',
    appId: '1:1094328447428:web:87db7e5ce8dc3be25db491',
    messagingSenderId: '1094328447428',
    projectId: 'campus-navigation-aa5ba',
    authDomain: 'campus-navigation-aa5ba.firebaseapp.com',
    storageBucket: 'campus-navigation-aa5ba.firebasestorage.app',
    measurementId: 'G-H7XNK5BLPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4_Ni3iQPDPthL7GZO7F9wd3ZkdcwQSk8',
    appId: '1:1094328447428:android:aa7ae7df747080a15db491',
    messagingSenderId: '1094328447428',
    projectId: 'campus-navigation-aa5ba',
    storageBucket: 'campus-navigation-aa5ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIKHmll0c-kEJqQ1vJFt2jSssEtw2813s',
    appId: '1:1094328447428:ios:feaec8752bb236df5db491',
    messagingSenderId: '1094328447428',
    projectId: 'campus-navigation-aa5ba',
    storageBucket: 'campus-navigation-aa5ba.firebasestorage.app',
    iosBundleId: 'com.example.campusNavigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIKHmll0c-kEJqQ1vJFt2jSssEtw2813s',
    appId: '1:1094328447428:ios:feaec8752bb236df5db491',
    messagingSenderId: '1094328447428',
    projectId: 'campus-navigation-aa5ba',
    storageBucket: 'campus-navigation-aa5ba.firebasestorage.app',
    iosBundleId: 'com.example.campusNavigation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR-Nndek8zOrmeNL4Zo_c5PVxjl-QI9xI',
    appId: '1:1094328447428:web:fc924ea43d186aa55db491',
    messagingSenderId: '1094328447428',
    projectId: 'campus-navigation-aa5ba',
    authDomain: 'campus-navigation-aa5ba.firebaseapp.com',
    storageBucket: 'campus-navigation-aa5ba.firebasestorage.app',
    measurementId: 'G-XRQFXS0251',
  );
}
